
services:
  cotizador-mysql:
    image: mysql:8.0
    container_name: cotizador-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  cotizador-app:
    image: tu-usuario-docker/cotizador-app:latest
    build: .
    container_name: cotizador-app-backend
    restart: always
    depends_on:
      cotizador-mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Pasa las variables a tu aplicación Spring Boot
      SPRING_DATASOURCE_URL: jdbc:mysql://cotizador-mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      # Aquí añadirás más variables en el futuro (claves de Stripe, Google, etc.)
      # STRIPE_API_KEY: ${STRIPE_API_KEY}
      # GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

volumes:
  mysql-data:
    driver: local